### ISSUE TITLE
pip install xgboost fails

### ISSUE THREAD

**Issue by petronetto** [Petronetto/machine-learning-alpine#3]
I believe tha could be something related to the `gcc` version. The container is using `gcc 6`, and some issues suggests use `gcc 5`

```
  Downloading xgboost-0.7.post3.tar.gz (450kB)
    Complete output from command python setup.py egg_info:
    + pwd
    + oldpath=/tmp/pip-build-b1rdmj3c/xgboost
    + cd ./xgboost/
    + [[  == darwin* ]]
    + LIB_XGBOOST=libxgboost.so
    + make lib/libxgboost.so -j4
    Makefile:31: MAKE [make] - checked OK
    g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/common/hist_util.o src/common/hist_util.cc >build/common/hist_util.d
    g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
    g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/common.cc -o build/common/common.o
    g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/logging.cc -o build/logging.o
    g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/hist_util.cc -o build/common/hist_util.o
    g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/learner.cc -o build/learner.o
    In file included from include/xgboost/logging.h:11:0,
                     from src/logging.cc:7:
    /tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include/dmlc/logging.h:18:22: fatal error: execinfo.h: No such file or directory
    compilation terminated.
    Makefile:140: recipe for target 'build/logging.o' failed
    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from /tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include/dmlc/io.h:14:0,
                     from src/learner.cc:7:
    /tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/include/dmlc/./logging.h:18:22: fatal error: execinfo.h: No such file or directory
    compilation terminated.
    Makefile:140: recipe for target 'build/learner.o' failed
    make: *** [build/learner.o] Error 1
    In file included from rabit/include/rabit/./internal/../../dmlc/io.h:14:0,
                     from rabit/include/rabit/./internal/../serializable.h:12,
                     from rabit/include/rabit/./internal/engine.h:10,
                     from rabit/include/rabit/rabit.h:32,
                     from src/common/./sync.h:11,
                     from src/common/hist_util.cc:10:
    rabit/include/rabit/./internal/../../dmlc/./logging.h:18:22: fatal error: execinfo.h: No such file or directory
    compilation terminated.
    Makefile:140: recipe for target 'build/common/hist_util.o' failed
    make: *** [build/common/hist_util.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo Building multi-thread xgboost failed
    Building multi-thread xgboost failed
    + echo Start to build single-thread xgboost
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /tmp/pip-build-b1rdmj3c/xgboost/xgboost
    /bin/sh: cd: line 1: can't cd to R-package/src
    + make lib/libxgboost.so -j4 USE_OPENMP=0
    Makefile:31: MAKE [make] - checked OK
    Makefile:43: /tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target '/tmp/pip-build-b1rdmj3c/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b1rdmj3c/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-build-b1rdmj3c/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-build-b1rdmj3c/xgboost/xgboost/libxgboost.so
    /tmp/pip-build-b1rdmj3c/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-build-b1rdmj3c/xgboost/xgboost/./lib/libxgboost.so
    /usr/xgboost/libxgboost.so

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b1rdmj3c/xgboost/
```

**Comment by petronetto** [comment]
Solved installing `libexecinfo-dev`

**Comment by datduonguva** [comment]
> Solved installing `libexecinfo-dev`

This method works on alpine3.9
